version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: nexus-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    command: --replSet rs0 --bind_ip localhost,mongodb
    networks:
      - nexus-network

volumes:
  mongo_data:

networks:
  nexus-network:
    driver: bridge
