branches:
  - main
  - name: "beta"
    prerelease: true
  - name: "alpha"
    prerelease: true

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/npm"
  - "@semantic-release/github"
  - "@semantic-release/git"

preset: "angular"

tagFormat: "v${version}"

analyzeCommits:
  preset: "angular"
  releaseRules:
    - type: "docs"
      scope: "README"
      release: "patch"
    - type: "refactor"
      release: "patch"
    - type: "style"
      release: "patch"
    - type: "perf"
      release: "patch"
    - type: "test"
      release: "patch"
    - type: "build"
      release: "patch"
    - type: "ci"
      release: "patch"
    - type: "chore"
      scope: "deps"
      release: "patch"
    - type: "revert"
      release: "patch"
    - type: "feat"
      release: "minor"
    - type: "fix"
      release: "patch"
    - type: "breaking"
      release: "major"
    - type: "security"
      release: "patch"

generateNotes:
  preset: "angular"
  presetConfig:
    types:
      - type: "feat"
        section: "Features"
      - type: "fix"
        section: "Bug Fixes"
      - type: "perf"
        section: "Performance Improvements"
      - type: "revert"
        section: "Reverts"
      - type: "docs"
        section: "Documentation"
      - type: "style"
        section: "Styles"
      - type: "refactor"
        section: "Code Refactoring"
      - type: "test"
        section: "Tests"
      - type: "build"
        section: "Build System"
      - type: "ci"
        section: "Continuous Integration"
      - type: "chore"
        section: "Chores"
      - type: "security"
        section: "Security"

prepare:
  - path: "@semantic-release/changelog"
    changelogFile: "CHANGELOG.md"
  - path: "@semantic-release/npm"
    npmPublish: false
  - path: "@semantic-release/git"
    assets:
      - "CHANGELOG.md"
      - "package.json"
      - "package-lock.json"
    message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}'

publish:
  - "@semantic-release/github"

success:
  - "@semantic-release/github"

fail:
  - "@semantic-release/github"
